# Домашнее задание к лекции "Функции"

Вам нужно помочь секретарю автоматизировать работу. Для этого нужно написать программу, которая будет на основе хранимых данных исполнять пользовательские команды.

Исходные данные имеют следующую структуру:

1. перечень всех документов
```
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
```
2. перечень полок, на которых хранятся документы (если документ есть в documents, то он обязательно должен быть и в directories)
```
directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}
```

Общие требования к программе:
- код должен быть грамотно декомпозирован (каждая функция отвечает за свою конкретную задачу, дублирующийся функционал переиспользуется, а его код не повторяется);
- в коде отсутствуют глобальные переменные (за исключением **documents** и **directories**);
- пользовательский ввод обрабатывается в цикле **while** до тех пор, пока пользователь явно не завершит программу (вводом команды "**q**").

## Задание 1

### Пункт 1. Пользователь по команде "*p*" может узнать владельца документа по его номеру

Примеры работы:

1.

```
Введите команду:
p

Введите номер документа:
10006
```
Результат:  
`Владелец документа: Аристарх Павлов`

2.
```
Введите команду:
p

Введите номер документа:
12345
```
Результат:  
`Документ не найден в базе`

### Пункт 2. Пользователь по команде "*s*" может по номеру документа узнать на какой полке он хранится

Примеры работы:

1.

```
Введите команду:
s

Введите номер документа:
10006
```
Результат:  
`Документ хранится на полке: 2`

2.
```
Введите команду:
p

Введите номер документа:
12345
```
Результат:  
`Документ не найден в базе`

### Пункт 3. Пользователь по команде "*l*" может увидеть полную информацию по всем документам

Пример работы:

```
Введите команду:
l
```

Результат:  
```
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

### Пункт 4. Пользователь по команде "*ads*" может добавить новую полку

Примеры работы:

1.

```
Введите команду:
ads

Введите номер полки:
10
```
Результат:  
`Полка добавлена. Текущий перечень полок: 1, 2, 3, 10.`

2.
```
Введите команду:
ads

Введите номер полки:
1
```
Результат:  
`Такая полка уже существует. Текущий перечень полок: 1, 2, 3.`

### Пункт 5. Пользователь по команде "*ds*" может удалить существующую полку из данных (только если она пустая)

Примеры работы:

1.

```
Введите команду:
ds

Введите номер полки:
3
```
Результат:  
`Полка удалена. Текущий перечень полок: 1, 2.`

2.
```
Введите команду:
ds

Введите номер полки:
1
```
Результат:  
`На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: 1, 2, 3.`

3.
```
Введите команду:
ds

Введите номер полки:
4
```
Результат:  
`Такой полки не существует. Текущий перечень полок: 1, 2, 3.`

In [97]:
#перечень всех документов
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]

directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}

def request_document_number():
    num_doc_request = input('Введите номер документа: ')
    return num_doc_request

def owner_by_number(num_doc_owner): # поиcк владельца документа по его номеру
    for element in documents:
        if num_doc_owner == element['number']:
            return element['name']

def print_p():    # вывод информации по кнопке 'p'
    document_number_p = request_document_number()
    if owner_by_number(document_number_p) == None:
        print('Документ не найден в базе')
    else:
        print('Владелец документа: ', owner_by_number(document_number_p))
        
def find_shelf(num_doc_find): # поиск номера полки по номеру документа
    for key, value in directories.items():
        if num_doc_find in value:
            return key

def print_s():    # вывод информации по кнопке 's'
    document_number_s = request_document_number()
    if find_shelf(document_number_s) == None:
        print('Документ не найден в базе')
    else:
        print('Документ хранится на полке: ', find_shelf(document_number_s))
        
def info_all_docs(): #вывод информации по кнопке 'l'
    for element in documents:
        print('№: ', element['number'], ', тип: ', element['type'], end='')
        print(', владелец: ', element['name'], ', полка хранения: ', find_shelf(element['number']))

def list_shelf(): # вывод списка полок
    counter = 1
    for row in directories:
        if counter !=len(directories):
            print(row, end=', ')
        else:
            print(row, end='.')
        counter +=1
    print()

def request_shelf_number():
    num_shelf_request = input('Введите номер полки: ')
    return num_shelf_request
        
def add_shelf(): #Пользователь по команде "ads" может добавить новую полку
    num_shelf_add = request_shelf_number()
    if num_shelf_add in directories:
        print('Такая полка уже существует. Текущий перечень полок: ', end='')
        list_shelf()
    else:
        directories.setdefault(num_shelf_add,[])
        print('Полка добавлена. Текущий перечень полок: ', end='')
        list_shelf()

def del_shelf(): #Пользователь по команде "ds" может удалить существующую полку из данных (только если она пустая)
    num_shelf_del = request_shelf_number()
    if num_shelf_del not in directories:
        print('Такой полки не существует. Текущий перечень полок: ', end='')
        list_shelf()
    elif len(directories.get(num_shelf_del)) != 0:
        print('На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: ', end='')
        list_shelf()
    elif len(directories.get(num_shelf_del)) == 0:
        del(directories[num_shelf_del])
        print('Полка удалена. Текущий перечень полок: ', end='')
        list_shelf()

while True:
    command = input('Введите команду ') 
    if command == 'p': # Пользователь по команде "p" может узнать владельца документа по его номеру
        print_p()
    elif command == 's': #Пользователь по команде "s" может по номеру документа узнать на какой полке он хранится
        print_s()
    elif command == 'l': # Пользователь по команде "l" может увидеть полную информацию по всем документам
        info_all_docs()
    elif command == 'as': # Пользователь по команде "as" может добавить новую полку¶
        add_shelf()
    elif command == 'ds': # Пользователь по команде "ds" может удалить существующую полку из данных (только если она пустая)
        del_shelf()
    elif command == 'q':
        break

Введите команду p
Введите номер документа: 10006
Владелец документа:  Аристарх Павлов
Введите команду 12345
Введите команду s
Введите номер документа: 10006
Документ хранится на полке:  2
Введите команду 12345
Введите команду l
№:  2207 876234 , тип:  passport, владелец:  Василий Гупкин , полка хранения:  1
№:  11-2 , тип:  invoice, владелец:  Геннадий Покемонов , полка хранения:  1
№:  10006 , тип:  insurance, владелец:  Аристарх Павлов , полка хранения:  2
Введите команду as
Введите номер полки: 10
Полка добавлена. Текущий перечень полок: 1, 2, 3, 10.
Введите команду as
Введите номер полки: 1
Такая полка уже существует. Текущий перечень полок: 1, 2, 3, 10.
Введите команду ds
Введите номер полки: 3
Полка удалена. Текущий перечень полок: 1, 2, 10.
Введите команду ds
Введите номер полки: 1
На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: 1, 2, 10.
Введите команду ds
Введите номер полки: 4
Такой полки не существует. Текущий перечень полок: 1, 2, 10.
Введ

## Задание 2 (необязательное)

Вам необходимо дополнить программу из задания 1 более продвинутыми командами.

### Пункт 1. Пользователь по команде "*ad*" может добавить новый документ в данные

Примеры работы:

1.

```
Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
3
```
Результат:  
```
Документ добавлен. Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№: 42, тип: multipassport, владелец: R2D2, полка хранения: 3
```

2.
```
Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
4
```
Результат:  
```
Такой полки не существует. Добавьте полку командой as. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

### Пункт 2. Пользователь по команде "*d*" может удалить документ из данных

Примеры работы:

1.

```
Введите команду:
d

Введите номер документа:
10006
```
Результат:  
```
Документ удален. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
```

2.
```
Введите команду:
d

Введите номер документа:
123456
```
Результат:  
```
Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

### Пункт 3. Пользователь по команде "*m*" может переместить документ с полки на полку

Примеры работы:

1.

```
Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
3
```
Результат:  
```
Документ перемещен. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 3
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

2.
```
Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
10
```
Результат:  
`Такой полки не существует. Текущий перечень полок: 1, 2, 3.`

3.
```
Введите команду:
m

Введите номер документа:
42
Введите номер полки:
2
```
Результат:  
```
Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

In [125]:
#перечень всех документов
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]

directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}

def del_document_shelf(document_number_del_sh): # удаление номера документа c полки, полку находит сам
    directories[find_shelf(document_number_del_sh)].remove(document_number_del_sh)
    
def del_document_documents(document_number_del_doc): # удаление документа из документов по номеру документа
    index = 0
    for el in documents:
        if document_number_del_doc in el.values():
            del(documents[index])
        index += 1
    
def add_document_shelf(shelf_number_add, document_number_add): # добавление номера документа в указанную полку
    directories[shelf_number_add].append(document_number_add)

def add_document_documents(document_type_add_f, num_doc_add_f, document_owner_add_f):
    documents.append(dict(zip(['type','number','name'],[document_type_add_f,num_doc_add_f,document_owner_add_f])))
    
def request_document_number(): # запрос и получение номер документа
    num_doc_request = input('Введите номер документа: ')
    return num_doc_request

def request_shelf_number():    # запрос и получение номера полки
    num_shelf_request = input('Введите номер полки: ')
    return num_shelf_request

def request_document_type(): # запрос и получение типа документа
    document_type = input('Введите тип документа: ')
    return document_type

def request_document_owner(): # запрос и получение владельца документа
    document_owner = input('Введите владельца документа: ')  
    return document_owner

def request_storage_shelf(): # запрос и получение полка для хранения
    storage_shelf = input('Введите полку для хранения: ')    
    return storage_shelf

def owner_by_number(num_doc_owner): # поиcк владельца документа по его номеру
    for element in documents:
        if num_doc_owner == element['number']:
            return element['name']

def find_shelf(num_doc_find): # поиск номера полки по номеру документа
    for key, value in directories.items():
        if num_doc_find in value:
            return key

def print_p():    # вывод информации по кнопке 'p'
    document_number_p = request_document_number() # запрос и получение номер документа
    if owner_by_number(document_number_p) == None: # вызов функции поиcк владельца документа по его номеру и условие
        print('Документ не найден в базе')
    else:
        print('Владелец документа: ', owner_by_number(document_number_p)) # вызов функции поиcк владельца документа по его номеру и условие
        
def print_s():    # вывод информации по кнопке 's'
    document_number_s = request_document_number() # запрос и получение номер документа
    if find_shelf(document_number_s) == None: # поиск номера полки по номеру документа и условие
        print('Документ не найден в базе')
    else:
        print('Документ хранится на полке: ', find_shelf(document_number_s)) # поиск номера полки по номеру документа
        
def info_all_docs(): #вывод информации по кнопке 'l'
    print('Текущий список документов:')
    for element in documents:
        print('№: ', element['number'], ', тип: ', element['type'], end='')
        print(', владелец: ', element['name'], ', полка хранения: ', find_shelf(element['number']))

def list_shelf(): # вывод списка полок
    counter = 1
    print('Текущий список полок:')
    for row in directories:
        if counter !=len(directories):
            print(row, end=', ')
        else:
            print(row, end='.')
        counter +=1
    print()
    
def list_doc_shelf():
    for key, value in directories.items():
        print('Номер полки - ',key, '. Документы:', value)

def add_shelf(): #Пользователь по команде "as" может добавить новую полку
    num_shelf_add = request_shelf_number() # вызов функции запрос и получение номера полки
    if num_shelf_add in directories:
        print('Такая полка уже существует. ', end='')
        list_shelf() # вызов функции вывод списка полок
    else:
        directories.setdefault(num_shelf_add,[])
        print('Полка добавлена. ', end='')
        list_shelf() # вызов функции вывод списка полок

def del_shelf(): #Пользователь по команде "ds" может удалить существующую полку из данных (только если она пустая)
    num_shelf_del = request_shelf_number() # вызов функции запрос и получение номера полки
    if num_shelf_del not in directories:
        print('Такой полки не существует. ', end='')
        list_shelf() # вызов функции вывод списка полок
    elif len(directories.get(num_shelf_del)) != 0:
        print('На полке есть документы, удалите их перед удалением полки. ', end='')
        list_shelf() # вызов функции вывод списка полок
    else:
        del(directories[num_shelf_del]) # вызов функции удалении полки
        print('Полка удалена. ', end='')
        list_shelf() # вызов функции вывод списка полок

def move_document(): # Пользователь по команде "m" может переместить документ с полки на полку
    document_number_move = request_document_number() # запрос и получение номер документа
    shelf_number_move = request_shelf_number()    # запрос и получение номера полки
    if shelf_number_move not in directories: 
        print('Такой полки не существует.', end='')
        list_shelf()
    elif find_shelf(document_number_move) == None:
        print('Документ не найден в базе.')
        info_all_docs()
    else:
        del_document_shelf(document_number_move)
        add_document_shelf(shelf_number_move, document_number_move)
        print('Документ перемещен.')
        info_all_docs()
        list_doc_shelf()
            
def del_document():# Пользователь по команде “d” может удалить документ из данных
    document_number_del = request_document_number() # запрос и получение номер документа
    if find_shelf(document_number_del) == None:
        print('Документ не найден в базе.')
        info_all_docs()
    else:
        del_document_documents(document_number_del)
        del_document_shelf(document_number_del)
        print('Документ удален.')
        info_all_docs()
        list_doc_shelf()

def add_document(): # Пользователь по команде “ad” может добавить новый документ в данные
    document_type_add = request_document_type() # запрос и получение типа документа
    num_doc_add = request_document_number() # запрос и получение номер документа
    document_owner_add = request_document_owner() # запрос и получение владельца документа
    storage_shelf_add = request_storage_shelf() # запрос и получение полка для хранения
    if storage_shelf_add not in directories: 
        print('Такой полки не существует. Добавьте полку командой as.')
        info_all_docs()
    else:
        add_document_documents(document_type_add, num_doc_add, document_owner_add)
        add_document_shelf(storage_shelf_add, num_doc_add) # добавление номера документа в указанную полку
        print('Документ добавлен. ', end='')
        info_all_docs()
        list_doc_shelf()

while True:
    command = input('Введите команду ') 
    if   command == 'p':  # Пользователь по команде "p" может узнать владельца документа по его номеру
        print_p()
    elif command == 's':  # Пользователь по команде "s" может по номеру документа узнать на какой полке он хранится
        print_s()
    elif command == 'l':  # Пользователь по команде "l" может увидеть полную информацию по всем документам
        info_all_docs()
        list_shelf()
        list_doc_shelf()
    elif command == 'as': # Пользователь по команде "as" может добавить новую полку¶
        add_shelf()
    elif command == 'ds': # Пользователь по команде "ds" может удалить существующую полку из данных (только если она пустая)
        del_shelf()
    elif command == 'q':  # выход из программы
        break
    elif command == 'ad': # Пользователь по команде "ad" может добавить новый документ в данные
        add_document()
    elif command == 'd':  # Пользователь по команде "d" может удалить документ из данных
        del_document()
    elif command == 'm':  # Пользователь по команде "m" может переместить документ с полки на полку
        move_document()

Введите команду ad
Введите тип документа: 42
Введите номер документа: multipassport
Введите владельца документа: R2D2
Введите полку для хранения: 3
Документ добавлен. Текущий список документов:
№:  2207 876234 , тип:  passport, владелец:  Василий Гупкин , полка хранения:  1
№:  11-2 , тип:  invoice, владелец:  Геннадий Покемонов , полка хранения:  1
№:  10006 , тип:  insurance, владелец:  Аристарх Павлов , полка хранения:  2
№:  multipassport , тип:  42, владелец:  R2D2 , полка хранения:  3
Номер полки -  1 . Документы: ['2207 876234', '11-2']
Номер полки -  2 . Документы: ['10006']
Номер полки -  3 . Документы: ['multipassport']
Введите команду ad
Введите тип документа: 42
Введите номер документа: multipassport
Введите владельца документа: R2D2
Введите полку для хранения: 4
Такой полки не существует. Добавьте полку командой as.
Текущий список документов:
№:  2207 876234 , тип:  passport, владелец:  Василий Гупкин , полка хранения:  1
№:  11-2 , тип:  invoice, владелец:  Геннадий Покем

#### ПРИМЕЧАНИЕ
Домашнее задание сдается ссылкой на репозиторий [GitHub](https://github.com/).
Не сможем проверить или помочь, если вы пришлете:
- файлы;
- архивы;
- скриншоты кода.

Все обсуждения и консультации по выполнению домашнего задания ведутся только на соответствующем канале в slack.

##### Как правильно задавать вопросы аспирантам, преподавателям и коллегам
Прежде чем задать вопрос, попробуйте найти ответ в интернете. Навык самостоятельного поиска информации — один из важнейших. Каждый практикующий специалист любого уровня делает это ежедневно.

Сформулируйте вопрос по алгоритму:  
1) Что я делаю?  
2) Какого результата я ожидаю?  
3) Как фактический результат отличается от ожидаемого?  
4) Что я уже попробовал сделать, чтобы исправить проблему?  

По возможности прикрепите к вопросу скриншоты либо ссылки на код. Не выкладывайте все решение, оставляйте только проблемный и воспроизводимый участок кода.